config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'company_reviews/index'
  get 'student_reviews/index'
  get 'student_feeds', to: 'student_feeds#new'
  post 'student_reviews', to: 'student_reviews#index'
  post 'company_reviews', to: 'company_reviews#index'
  resources :student_feeds
  resources :company_reviews
  resources :student_reviews
  get 'welcome/index'

  

  root 'welcome#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_and_belongs_to_many :student_feeds
	has_many :company_review
end

app/models/company_datum.rb
class CompanyDatum < ActiveRecord::Base
end

app/models/company_review.rb
class CompanyReview < ActiveRecord::Base
  belongs_to :company
end

app/models/student_feed.rb
class StudentFeed < ActiveRecord::Base
  has_and_belongs_to_many :companies
  validates :rollno, presence: true
  validates :email, presence: true, 
  email_format: { message: "doesn't look like an email address" }
  validates :year, presence: true, 
  			length: {is: 4}
  validates :feeback, presence: true
  #validates :company_id, presence: true
  validates :name, presence: true
  #validates :companyname, inclusion: {in Article.all}			
end

app/models/student_review.rb
class StudentReview < ActiveRecord::Base
  belongs_to :student_feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def show
	end
end

app/controllers/company_reviews_controller.rb
class CompanyReviewsController < ApplicationController
  before_action :set_companyreview, only: [:show]
	def index
		@company= Company.order(:compname)
		begin
    		@companyreview= CompanyReview.new(post_params)
    		@user= CompanyReview.where(company_id: @companyreview.company_id)
    	rescue
    		@companyreview= CompanyReview.new
    		@user= CompanyReview.all
    	end
	end
	def post_params
  		params.require(:company_review).permit(:company_id )
  end
  def show
  end
  def set_companyreview
    @companyreview= CompanyReview.find(params[:id]) 
  end

end

app/controllers/student_feeds_controller.rb
class StudentFeedsController < ApplicationController
  before_action :set_studentfeed, only: [:show]  
  def new
    @studentfeed= StudentFeed.new
  	@company1= Company.all
    @company= @company1.select("id, compname")

  end
  def create
  	@studentfeed= StudentFeed.new(post_params)
    @company= Company.all
    respond_to do |format|
      if @studentfeed.save
        #@studentfeed.companyname= Company.find(@studentfeed.company_id).compname
        @studentfeed.save
        flash[:notice] = "Widget was successfully created."
        format.html { redirect_to student_reviews_index_url}
      else
        format.html { render :new }
        format.json { render json: @studentfeed.errors, status: :unprocessable_entity }
      end

    end
  end
  def show
  end

  private
  def set_studentfeed
    @studentfeed= StudentFeed.find(params[:id]) 

  end
  def post_params
  	params.require(:student_feed).permit(:rollno, :email, :year, :feeback,  :name, :stream, :phone_no, :focus, company_ids: []  )
  end

end

app/controllers/student_reviews_controller.rb
class StudentReviewsController < ApplicationController
	def index
		@company= Company.order(:compname)

		begin
    		@studentreview= StudentReview.new(post_params)
    		@user1= Company.find(@studentreview.company_id)
        	@user= @user1.student_feeds #.paginate(page: params[:page], per_page: 6)

    	rescue
    		@studentreview= StudentReview.new
    		@user= StudentFeed.all #.paginate(page: params[:page], per_page: 6)
    	end
	end
	def post_params
  		params.require(:student_review).permit(:company_id )
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #layout 'standard'
 	def index
		@company= Company.all
		begin
    		@companyreview= CompanyReview.new(post_params)
    		@user= CompanyReview.where(company_id: @companyreview.company_id)
    	rescue
    		@companyreview= CompanyReview.new
    		@user= CompanyReview.all
    	end
	end
	def post_params
  		params.require(:company_review).permit(:company_id )
  	end
  def set_studentfeed
    @studentfeed= StudentFeed.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_reviews_helper.rb
module CompanyReviewsHelper
end

app/helpers/student_feeds_helper.rb
module StudentFeedsHelper
end

app/helpers/student_reviews_helper.rb
module StudentReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/company_reviews/index.html.erb
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  

<header>
  <nav id="header-nav" class="navbar navbar-default">
    <div class="container" id="header-container" >
      <div class="navbar-header">
        <div class="navbar-brand">
          <h1 id="comp-head">IIITB Placement Reviews</h1>
        </div>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collap-nav" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"> </span>
              <span class="icon-bar"> </span>
              <span class="icon-bar"> </span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="collap-nav">
        <ul id="nav-list" class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", "/welcome/index" %></li>
          <li><%= link_to "Feedback Form", "/student_feeds/new" %></li>
          <li><%= link_to "Student's Reviews", "/student_reviews/index" %></li>
          <li class="active"><%= link_to "Company's Reviews", "/company_reviews/index" %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>


<tbody>
<h1 id="sub-comp-head"> COMPANY REVIEWS </h1>
  <%= form_for(@companyreview) do |f| %>
    <%= f.collection_select :company_id , @company, :id, :compname, {:prompt => 'Select Company'},{:class=>"dropdown"}%>
    <%= f.submit "search", :class => "button"%>
    <% end %>
     <% @user.each do |companyreview| %>

    <div>
    <div class="w3-content" style="max-width:1400px">
      <div class="col-md-2"></div>
      <div class="row">
      <div class="col-xs-12 col-md-8" id = "box">
        <div class="w3-col ">
          <div class="w3-card-4 w3-margin w3-white">
            <div class="w3-container w3-padding-8">
              <h3 ><b><%= companyreview.name %> (<%= companyreview.year %>)</b></h3>
              
            </div>

            <div class="w3-container">
            <% if companyreview.feedback.length > 1000 %>
              <%=raw companyreview.feedback.truncate(1000) %>
              <p><b><%= link_to '<button class="w3-button w3-padding-large w3-white w3-border">READ MORE >>></button>'.html_safe, companyreview, :target=>"_blank" %></b></p>
              <% else %>
              <%=raw companyreview.feedback %>
            <% end %>

        
            </div>
          </div>
        </div>
      </div>
    </div>

    </div>
    <hr style="margin:1px;">
    <% end %>
  
 </tbody>

app/views/company_reviews/show.html.erb
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <header>
      <nav id="header-nav" class="navbar navbar-default">
        <div class="container" id="header-container" >
          <div class="navbar-header">
            <div class="navbar-brand">
              <h1 id="review-head">IIITB Placement Reviews</h1>
            </div>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collap-nav" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle Navigation</span>
                  <span class="icon-bar"> </span>
                  <span class="icon-bar"> </span>
                  <span class="icon-bar"> </span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="collap-nav">
            <ul id="nav-list" class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", "/welcome/index" %></li>
              <li><%= link_to "Feedback Form", "/student_feeds/new" %></li>
              <li class="active"><%= link_to "Student's Reviews", "/student_reviews/index" %></li>
              <li><%= link_to "Company's Reviews", "/company_reviews/index" %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <h1 id="sub-review-head">Company Review</h1>
     
     <div class="col-md-2"></div>
    <div class="row">
   <div class="col-xs-12 col-md-8" id = "box">
    <div class="w3-col">
      
      <div class="w3-card-4 w3-margin w3-white">
        <div class="w3-container w3-padding-8">
          <h3 ><b><%= @companyreview.name %> (<%= @companyreview.year %>)</b></h3>
        </div>

        <div class="w3-container">
          <p><%=raw @companyreview.feedback %></p>
          
        </div>
      </div>
     </div>

    </div>
    </div>

      <hr> 
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlacecomFeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

<footer class="panel-footer">
		<div class="row">
			<div class="col-lg-4 col-xs-3"></div>
			<div class="col-lg-4 col-xs-3"></div>
			<div class="col-lg-4 col-xs-6"><h3>IIIT-Bangalore</h3>
				<!--26/C, Electronics City,<br>
				Hosur Road, Bangalore - 560100 <br>-->
				Phone: +91 80 4140 7777/ 2852 7627 <br>
				Fax: +91 80 4140 7704<br>
				<span id="copyright">&copy;All Rights Reserved. Developed by Zense | IIIT B</span> </div>
		</div>
	
</footer>
<script>
      $(document).ready(function(){
        $(".panel-footer").fadeIn(1500);
      });
</script>
</body>
</html>

app/views/layouts/standard.html.erb
<!doctype html>
<html>
<head>
<%= stylesheet_link_tag "bootstarp.min" %>
<%= stylesheet_link_tag "welcome" %>
</head>
<body>
</body>
</html>

app/views/student_feeds/index.html.erb
<<<<<<< HEAD
<!-- <tbody>
=======

<tbody>

>>>>>>> 27eb65679de39ec8ba6e9cf881be781fef1a4c00
<h1> STUDENT REVIEWS </h1>
  <p id="notice"><%= notice %></p>
  <div class = "main">
  <table class = "col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <tr>
    <th width= 10%>Roll Number</th>
    <th width= 15%>Comapany Name</th>
    <th width= 75%>Student Review</th>
  </tr>
<% @studentfeeds.each do |studentfeed| %>
  <tr>
    <td width= 10%><%= studentfeed.rollno %></td>
    <td width= 15%><%= studentfeed.companyname %></td>
    <td width= 75%>
      <% if studentfeed.feeback.length > 1000 %>
        <%= truncate studentfeed.feeback, length:1000 %>
        <%= link_to '...read more', studentfeed, :target=>"_blank" %> </td>
      <% else %>
        <%= studentfeed.feeback %>
      <% end %>
    <td><%= studentfeed.feeback %></td>
  </tr>
<% end %>
</table>
</div>
<br>
<div class = "link" >
<%= link_to 'New StudentFeed', new_student_feed_path %></div>
</tbody>
 -->
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
 <body>
  <p id="notice"><%= notice %></p>
  <div class = "main">
<% @studentfeeds.each do |studentfeed| %>
<div class="w3-content" style="max-width:1400px">

<div class="w3-row">

<div class="w3-col l8 s12">
  <div class="w3-card-4 w3-margin w3-white">
    <div class="w3-container w3-padding-8">
      <h3><b><%= studentfeed.rollno %></b></h3>
      <h5><%= studentfeed.companyname %> <span class="w3-opacity">April 7, 2014</span></h5>
    </div>

    <div class="w3-container">
      <% if studentfeed.feeback.length > 1000 %>
        <%= truncate studentfeed.feeback, length:1000 %>
        <%= link_to '...read more', studentfeed, :target=>"_blank" %> </td>
      <% else %>
        <%= studentfeed.feeback %>
      <% end %>
      
    </div>
  </div>
  </div>
  </div>
  </div>
  <hr>
  
  <% end %>
</body>

app/views/student_feeds/new.html.erb
<link rel="stylesheet" href="/stylesheets/font-awesome-4.7.0/css/font-awesome.min.css">



<header>
	<nav id="header-nav" class="navbar navbar-default">
		<div class="container" id="header-container" >
			<div class="navbar-header">
				<div class="navbar-brand">
					<h1 id="feed-head">IIITB Placement Reviews</h1>
				</div>
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collap-nav" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle Navigation</span>
        			<span class="icon-bar"> </span>
        			<span class="icon-bar"> </span>
        			<span class="icon-bar"> </span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="collap-nav">
				<ul id="nav-list" class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", "/welcome/index" %></li>
					<li class="active"><%= link_to "Feedback Form", "/student_feeds/new" %></li>
					<li><%= link_to "Student's Reviews", "/student_reviews/index" %></li>
					<li><%= link_to "Company's Reviews", "/company_reviews/index" %></li>
				</ul>
			</div>
		</div>
	</nav>
</header>

<!--<header>
	<nav id="header-nav" class="navbar navbar-default">
		<div class="container" id="header-container" >
			<div class="navbar-header">
				<div class="navbar-brand">
					<h1 id="sec-feed-head">FeedBack Form</h1>
				</div>
			</div>
		</div>
	</nav>			
</header>-->

<%= form_for(@studentfeed) do |f| %>

 <% if @studentfeed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studentfeed.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @studentfeed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1 id="sub-feed-head">FeedBack Form</h1>
<!--<div class="container">
	<div class="row">
		<span class="form-label col-xs-4"><%= f.label :Name %>*</span>
		<span class="form-fields col-xs-4"><%= f.text_field :name %></span>
		<div class="col-sm-4"></div>
	</div>

	<div class="row">
		<span class="form-label col-xs-4"><%= f.label :'Roll number' %>*</span>
		<span class="form-fields col-xs-4"><%= f.text_field :rollno %></span>
		<div class="col-sm-4"></div>
	</div>
	<div class="row" id="dropdrown">
		<div class="col-xs-4"></div>
		<span class="col-xs-4"><%= f.select :stream, ['iMtech', 'Mtech IT', 'Mtech esd', 'DigiSOC']%></span>
		<div class="col-xs-4"></div>
	</div>
	<div class="row">
		<span class="form-label col-xs-4"><%= f.label :Email %>*</span>
		<span class="form-fields col-xs-4"><%= f.text_field :email %></span>
		<div class="col-xs-4"></div>
	</div>

	<div class="row">
		<span class="form-label col-xs-4"><%= f.label :'Phone no.' %>*</span>
		<span class="form-fields col-xs-4"><%= f.text_field :phone_no %></span>
		<div class="col-sm-4"></div>
	</div>

	<div class="row">
		<span class="form-label col-xs-4"><%= f.label :Year %>*</span>
		<span class="form-fields col-xs-4"><%= f.text_field :year %></span>
		<div class="col-xs-4"></div>
	</div>
	<div class="row">
		<span class="form-label col-xs-4"><%= f.label :Feedback %>*</span>
		<span class="form-fields col-xs-4" id="feed-text"><%= f.text_area :feeback %></span>
		<div class="col-xs-4"></div>
	</div>
	<div class="row" id="dropdrown">
		<div class="col-xs-4"></div>
		<span class="col-xs-4"><%=  f.collection_select :company_ids, @company,:id,:compname , {},{multiple: true} %></span>
		<div class="col-xs-4"></div>
	</div>
	<div class="row" id="submit">
		<div class="col-xs-4"></div>
		<span class="col-xs-4"><%= f.submit %></span>
		<div class="col-xs-4"></div>
	</div>
</div>-->
<form class="form-horizontal feedback-form" id="feed-form">
	<div class="col-xs-1 col-md-4"></div>
		<div class="row">
			<div class="col-xs-8 col-md-6" id="box">
				<div class="row form-group">
					<!--<span class="form-label col-xs-4">
						<%= f.label :Name , :class => 'control-label' %>
							<span class="star">*</span>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-user fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.text_field :name , :class => 'form-control',placeholder: "Name" ,:required => true %>
					</span>
					<div class="col-sm-1"></div>
				</div>
				<div class="row form-group">
					<!--<span class="form-label col-xs-4">
						<%= f.label :'Roll number' , :class => 'control-label'%>
							<span class="star">*</span>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-registered fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.text_field :rollno , :class => 'form-control' , placeholder: "Roll Number" ,:required => true ,:maxlength => 11%>
					</span>
					<div class="col-sm-1"></div>	
				</div>
				<div class="row dropdown_feed" id="dropdown1">
					<!--<span class="form-label col-xs-4"><%= f.label :Stream %>
						<span class="star">*</span>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-graduation-cap fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.select :stream, ['iMtech', 'Mtech it', 'Mtech esd' ,'DigiSOC'] , {:prompt => 'Select Stream'}, { :class => 'sub-menu-parent',:required => true} %>	
					</span>
					<!--<div class="col-xs-1"></div>-->
				</div>
				<div class="row form-group">
					<!--<span class="form-label col-xs-4">
						<%= f.label :Email , :class => 'control-label'%>
							<span class="star">*</span>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-envelope fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.email_field :email , :class => 'form-control' ,placeholder: "Email" ,:required => true%>
					</span>
					<!--<div class="col-xs-1"></div>-->
				</div>
				<div class="row form-group">
					<!--<span class="form-label col-xs-4">
						<%= f.label :'Phone no.' , :class => 'control-label' %>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-mobile fa-3x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.telephone_field :phone_no , :class => 'form-control',placeholder: "Mobile Number" ,:maxlength => 11%>
					</span>
					<!--<div class="col-sm-1"></div>-->
				</div>
				<div class="row form-group">
					<!--<span class="form-label col-xs-4">
						<%= f.label :Year , :class => 'control-label'%>
							<span class="star">*</span>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-calendar fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.number_field :year , :class => 'form-control' ,placeholder: "Year:YYYY" ,:required => true , max: 3000,min: 2000%>
					</span>
					<!--<div class="col-xs-1"></div>-->
				</div>
				<!--<div class="row dropdown_feed" id="dropdown2">
					/*<span class="form-label col-xs-4">
						<%= f.label :Company , :class => 'control-label'%>
					</span>*/
					<span class="ccform-addon">
						<i class="fa fa-building-o fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%=f.collection_check_boxes :company_ids,@company,:id,
						:compname, {:prompt=> 'select companies'}, 
						 {:multiple=> true, :size=> 1}%> 
					</span>
					/*<div class="col-xs-4"></div>*/
				</div>-->
				<!-- <div class="row dropdown_feed" id="dropdown1">
					<span class="ccform-addon">
						<i class="fa fa-graduation-cap fa-2x"></i>
					</span>
					<span class="form-fields col-xs-4">
						<%= f.select :stream, ['Imtech', 'Mtech', 'Phd'] , {:prompt => 'Select Stream'}, { :class => 'sub-menu-parent'} %>	
					</span>
					
				</div> -->
				<div class="row dropdown_feed" id="dropdown1">
				    <span class="ccform-addon">
							<i class="fa fa-building-o fa-2x"></i>
					</span>
					<div class="form-fields col-xs-7">
						<%=  f.collection_select :company_ids, @company,:id,:compname , {},{multiple: true, id:'langOpt'} %>
					</div>   
				</div>
				

				<div class="row form-group">
					<!--<span class="form-label col-xs-4">
						<%= f.label :'Phone no.' , :class => 'control-label' %>
					</span>-->
					<span class="ccform-addon">
						<i class="fa fa-search fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7">
						<%= f.text_field :focus , :class => 'form-control',placeholder: "Key Focuses Ex:geekforgeeks, stackoverflow",:required => true ,:maxlength =>100%>
					</span>
					<!--<div class="col-sm-1"></div>-->
				</div>
				<div class="row form-group">
					<span class="ccform-addon">
						<i class="fa fa-comments-o fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7 col-md-7" id="feedtext">

						<%= f.text_area :feeback, class: "tinymce form-control",rows: 10 %>
					</span>
				</div>
			</div>
			<!--<div class="col-xs-12 col-md-5 box">
					<span class="form-label col-xs-4 col-md-3">
						<%= f.label :Feedback , :class => 'control-label'%>
							<span class="star">*</span>
					</span>
					<span class="ccform-addon">
						<i class="fa fa-comment fa-2x"></i>
					</span>
					<span class="form-fields col-xs-7 col-md-7" id="feedtext">
						<%= f.text_area :feeback , :class => 'form-control',placeholder: "Enter Feedback" %>
					</span>
			</div>-->
		</div>
	<script>
		console.log("abc")
	</script>
	<div class="col-xs-2 col-md-2"></div>	
	<div class="row" id="submit">
		<div class="col-xs-4"></div>
		<span class="col-xs-4">
			<%= f.submit 'Create Student feed', :class => 'submit_sub_btn'%>
		</span>
		<div class="col-xs-4"></div>
	</div>

</form>
<script src="/stylesheets/jquery.min.js"></script>
<script src="/stylesheets/jquery.multiselect.js"></script>
<script>
// var expanded = false;

// function showCheckboxes() {
//   var checkboxes = document.getElementById("checkboxes");
//   if (!expanded) {
//     checkboxes.style.display = "block";
//     expanded = true;
//   } else {
//     checkboxes.style.display = "none";
//     expanded = false;
//   }
// }
$('#langOpt').multiselect({
    columns: 1,
    placeholder: 'Select Company',
    search: true
});
</script>
<% end %>
<%= tinymce %>

app/views/student_reviews/index.html.erb
  <link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
   <body>
   <header>
    <nav id="header-nav" class="navbar navbar-default">
      <div class="container" id="header-container" >
        <div class="navbar-header">
          <div class="navbar-brand">
            <h1 id="review-head">IIITB Placement Reviews</h1>
          </div>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collap-nav" aria-expanded="false" aria-cfeedontrols="navbar">
            <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
                <span class="icon-bar"> </span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="collap-nav">
          <ul id="nav-list" class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", "/welcome/index" %></li>
            <li><%= link_to "Feedback Form", "/student_feeds/new" %></li>
            <li class="active"><%= link_to "Student's Reviews", "/student_reviews/index" %></li>
            <li><%= link_to "Company's Reviews", "/company_reviews/index" %></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <h1 id="sub-review-head">Student's Review</h1>
    <%= form_for(@studentreview) do |f| %>
    <%= f.collection_select :company_id , @company, :id, :compname, {:prompt => 'Select Company'},{:class=>"dropdown"}%>
    <%= f.submit "search", :class => "button"%>
    <% end %>
    
    <p id="notice"><%= notice %></p>

    <% @user.reverse.each do |studentfeed| %>
    <div>
    <div class="w3-content" style="max-width:1400px">
      <div class="col-md-2"></div>
      <div class="row">
      <div class="col-xs-12 col-md-8" id = "box">
        <div class="w3-col ">
          <div class="w3-card-4 w3-margin w3-white">
            <div class="w3-container w3-padding-8">
              <h3 ><b><%= studentfeed.name %></b></h3>
              <h5 class ="right"> <%= studentfeed.companyname %> <br><span class="w3-opacity" ><%= studentfeed.year %></span></h5>
            </div>

            <div class="w3-container">
            <b>Key Focus: </b><%=studentfeed.focus %>
            <hr>
            <b>Feedback:</b>
             <% if studentfeed.feeback.length > 1000 %>
              <%=raw studentfeed.feeback.truncate(1000) %>
              <p><b><%= link_to '<button class="w3-button w3-padding-large w3-white w3-border">READ MORE >>></button>'.html_safe, studentfeed, :target=>"_blank" %></b></p>
              <% else %>
              <%=raw studentfeed.feeback %>
            <% end %>

        
            </div>
          </div>
        </div>
      </div>
    </div>

    </div>
    <hr style="margin:1px;">
    <% end %>
    
    </br>
    <%= link_to 'New StudentFeed', new_student_feed_path %></div>
  </body>